const Units = {
    NormalNaruto : "[Normal]Naruto",
    NormalSakura : "[Normal]Sakura",
    NormalSasuke : "[Normal]Sasuke",
    NormalTemari : "[Normal]Temari",
    NormalSasori : "[Normal]Sasori",
    NormalAnbu : "[Normal]Anbu",
    NormalSai : "[Normal]Sai",
    NormalYamato : "[Normal]Yamato",
    NormalKabuto : "[Normal]Kabuto",
    NormalKarin : "[Normal]Karin",
    //////////////////////////////////////////////////////////////////////////
    MagicJiraiya : "[Magic]Jiraiya",
    MagicKankuro : "[Magic]Kankuro",
    MagicOrochimaru : "[Magic]Orochimaru",
    MagicSasuke : "[Magic]Sasuke",
    MagicJugo : "[Magic]Jugo",
    MagicChoji : "[Magic]Choji",
    MagicShikamaru : "[Magic]Shikamaru",
    MagicZetsu : "[Magic]Zetsu",
    MagicTsunade : "[Magic]Tsunade",
    MagicKiba : "[Magic]Kiba",
    ////////////////////////////////////////////////////////////////////////////////////
    RareGamaken : `[Rare]Gamaken = MagicJiraiya + NormalNaruto + NormalSakura`,
    RareGaara : `[Rare]Gaara = MagicKankuro + NormalTemari + NormalSasori`,
    RareGuyTurtle : `[Rare]GuyTurtle = NormalAnbu + NormalSai + NormalTemari`,
    RareNaruto : `[Rare]Naruto = NormalNaruto + MagicJiraiya + NormalYamato`,
    RareManda : `[Rare]Manda = MagicOrochimaru + NormalKabuto + NormalSasuke`,
    RareSasori : `[Rare]Sasori = NormalSasori + MagicOrochimaru + NormalAnbu`,
    RareSasuke : `[Rare]Sasuke = MagicSasuke + NormalKarin + NormalKabuto`,
    RareSuigetsu : `[Rare]Suigetsu = NormalSasuke + NormalKarin + MagicJugo`,
    RareAsuma : `[Rare]Asuma = MagicChoji + NormalNaruto + NormalYamato`,
    RareAoba : `[Rare]Aoba = NormalYamato + NormalSai + MagicShikamaru`,
    RareInoichi : `[Rare]Inoichi = NormalSakura + NormalKabuto + MagicChoji`,
    RareIzumo : `[Rare]Izumo = NormalYamato + MagicShikamaru + NormalAnbu`,
    RareItachi : `[Rare]Itachi = MagicSasuke + MagicSasuke + NormalAnbu`,
    RareKarui : `[Rare]Karui = MagicChoji + NormalKarin + NormalSasuke`,
    RareKatsuyu : `[Rare]Katsuyu = MagicTsunade + MagicTsunade + NormalSakura`,
    RareKakashi : `[Rare]Kakashi = NormalSai + NormalNaruto + NormalSasuke`,
    RareKakuzu : `[Rare]Kakuzu = MagicZetsu + MagicChoji + NormalSasori`,
    RareKotetsu : `[Rare]Kotetsu = MagicShikamaru + MagicChoji + MagicTsunade`,
    RareMaskedMan : `[Rare]MaskedMan = MagicZetsu + MagicZetsu + MagicKankuro`,
    RareHaku : `[Rare]Haku = MagicJugo + MagicOrochimaru + NormalTemari`,
    RareHinata : `[Rare]Hinata = MagicKiba + NormalSakura + NormalSai`,
    ////////////////////////////////////////////////////////////////////////////////
    UniqueGamabunta : `[Unique]Gamabunta = RareGamaken + RareGamaken`,
    UniqueGamahiro : `[Unique]Gamahiro = RareGamaken + MagicZetsu + MagicShikamaru`,
    UniqueGaara : `[Unique]Gaara = RareGaara + RareKakashi`,
    UniqueRockLee : `[Unique]RockLee = RareGuyTurtle + RareGaara`,
    UniqueTenten : `[Unique]Tenten = NormalTemari + RareGuyTurtle + MagicTsunade`,
    UniqueKushina : `[Unique]Kushina = RareNaruto + RareMaskedMan`,
    UniqueNaruto : `[Unique]Naruto = RareNaruto + RareKakuzu`,
    UniqueJiraiya : `[Unique]Jiraiya = MagicJiraiya + MagicTsunade + RareNaruto`,
    UniqueSasori : `[Unique]Sasori = RareSasori + RareSasori`,
    UniqueKankuro : `[Unique]Kankuro = MagicKankuro + RareSasori + NormalSasori`,
    UniqueOmoi : `[Unique]Omoi = MagicKankuro + RareSasori + NormalAnbu + NormalNaruto`,
    UniqueDeidara : `[Unique]Deidara = RareMaskedMan + RareSasuke`,
    UniqueSai : `[Unique]Sai = NormalSai + NormalNaruto + MagicJugo + RareSasuke`,
    UniqueJugo : `[Unique]Jugo = MagicJugo + MagicJugo + RareSasuke + NormalKabuto`,
    UniqueSasuke : `[Unique]Sasuke = RareSuigetsu + NormalYamato + MagicJiraiya`,
    UniqueChojuro : `[Unique]Chojuro = RareSuigetsu + RareHaku`,
    UniqueWhiteZetsu : `[Unique]WhiteZetsu = MagicZetsu + NormalKarin + NormalKabuto + RareSuigetsu`,
    UniqueKisame : `[Unique]Kisame = RareAsuma + RareItachi`,
    UniqueEnma : `[Unique]Enma = RareAsuma + RareIzumo`,
    UniqueYuhiKurenai : `[Unique]YuhiKurenai = RareHinata + RareAsuma`,
    UniqueOrochimaru : `[Unique]Orochimaru = RareManda + RareKotetsu`,
    UniqueMitarashi : `[Unique]Mitarashi = MagicOrochimaru + RareManda + MagicSasuke`,
    UniqueYamanakaFu : `[Unique]YamanakaFu = RareInoichi + RareAoba`,
    UniqueSizune : `[Unique]Sizune = RareInoichi + RareKatsuyu`,
    UniqueIno : `[Unique]Ino = RareInoichi + MagicShikamaru + NormalSai`,
    UniqueItachi : `[Unique]Itachi = RareItachi + RareMaskedMan`,
    UniqueYamato : `[Unique]Yamato = NormalYamato + MagicTsunade + RareItachi`,
    UniqueKillerBee : `[Unique]KillerBee = RareKarui + RareAoba`,
    UniqueSamui : `[Unique]Samui = RareKarui + MagicTsunade + NormalKarin`,
    UniqueNagato : `[Unique]Nagato = MagicJiraiya + MagicJiraiya + RareKatsuyu`,
    UniqueKakashi : `[Unique]Kakashi = RareKakashi + RareHaku`,
    UniqueNoharaRin : `[Unique]NoharaRin = RareKakashi + RareMaskedMan`,
    UniqueZabuza : `[Unique]Zabuza = RareHaku + RareKakashi`,
    UniqueHinata : `[Unique]Hinata = RareHinata + NormalSai + NormalNaruto`,
    UniqueNeji : `[Unique]Neji = RareHinata + MagicKiba + MagicSasuke`,
    UniqueShino : `[Unique]Shino = MagicKiba + RareHinata + MagicShikamaru`,
    UniqueHidan : `[Unique]Hidan = RareKakuzu + RareIzumo`,
    UniqueKakuzu : `[Unique]Kakuzu = RareKakuzu + RareKotetsu`,
    UniqueAnko : `[Unique]Anko = MagicOrochimaru + RareManda + MagicSasuke`,
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    HiddenGamakichi : `[Hidden]Gamakichi = UniqueGamabunta + UniqueGamahiro + TypeGamakichi`,
    HiddenNaruto : `[Hidden]Naruto = UniqueNaruto + UniqueNagato + TypeSixtails`,
    HiddenMaki : `[Hidden]Maki = UniqueKakashi + UniqueGaara + TypeMaki`,
    HiddenHashirama : `[Hidden]Hashirama = UniqueItachi + UniqueYamato + TypeHashirama`,
    HiddenTobirama : `[Hidden]Tobirama = UniqueNaruto + UniqueAnko + TypeTobirama`,
    HiddenTemari : `[Hidden]Temari = UniqueKankuro + UniqueTenten + MagicKankuro + TypeTemari`,
    HiddenKurotsuchi : `[Hidden]Kurotsuchi = UniqueSai + UniqueDeidara + TypeKurotsuchi`,
    HiddenAkatsuchi : `[Hidden]Akatsuchi = UniqueTenten + UniqueWhiteZetsu + TypeAkatsuchi`,
    HiddenKitsuchi : `[Hidden]Kitsuchi = UniqueIno + UniqueOmoi + TypeKitsuchi`,
    HiddenTorune : `[Hidden]Torune = UniqueYamanakaFu + UniqueShino + TypeTorune`,
    HiddenOrochimaru : `[Hidden]Orochimaru = UniqueOrochimaru + UniqueJugo + TypeOrochimaru`,
    HiddenHanzo : `[Hidden]Hanzo = UniqueJiraiya + UniqueAnko + MagicTsunade + TypeHanzo`,
    HiddenKabuto : `[Hidden]Kabuto = UniqueYuhiKurenai + UniqueAnko + TypeSpy`,
    HiddenDanzo : `[Hidden]Danzo = UniqueKakashi + UniqueYamanakaFu + TypeDanzo`,
    HiddenJugo : `[Hidden]Jugo = UniqueJugo + UniqueJugo + TypeJugo`,
    HiddenHinata : `[Hidden]Hinata = UniqueHinata + UniqueShino + NormalKabuto + TypeHinata`,
    HiddenSasori : `[Hidden]Sasori = UniqueSasori + UniqueKankuro + TypeSasori`,
    HiddenJiraiya : `[Hidden]Jiraiya = UniqueJiraiya + UniqueGamabunta + TypeJiraiya`,
    HiddenShii : `[Hidden]Shii = UniqueKillerBee + UniqueOmoi + TypeShii`,
    HiddenKiba : `[Hidden]Kiba = UniqueYuhiKurenai + UniqueNeji + MagicKiba + TypeKiba`,
    HiddenKirin : `[Hidden]Kirin = UniqueItachi + UniqueSasuke + TypeKirin`,
    HiddenAo : `[Hidden]Ao = UniqueKisame + UniqueChojuro + TypeAo`,

    // HiddenSevenNinjaSworsdsman : `[Hidden] = ???? + Type`,
    // HiddenKushimaruKirarare : `[Hidden] = ???? + Type`,
    // HiddenHozukiMangetsu : `[Hidden] = ???? + Type`,
    // HiddenAmeyuriRingo : `[Hidden] = ???? + Type`,
    // HiddenZabuza : `[Hidden] = ???? + Type`,
    // HiddenJininAkebino : `[Hidden] = ???? + Type`,
    // HiddenFugukiSuikazan : `[Hidden] = ???? + Type`,
    // HiddenJinpachiMunashi : `[Hidden] = ???? + Type`,

    // i dont see these in game????
    HiddenAnko : `[Hidden]Anko = UniqueYuhiKurenai + UniqueOrochimaru + TypeAnko`,
    HiddenNinjado : `[Hidden]Ninjado = UniqueZabuza + UniqueRockLee + UniqueChojuro + TypeNinjado`,
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    TypeGamakichi : `Type in "Gamakichi"`,
    TypeSixtails : `Type in "Sixtails"`,
    TypeMaki : `Type in "Maki"`,
    TypeHashirama : `Type in "Hashirama"`,
    TypeTobirama : `Type in "Tobirama"`,
    TypeTemari : `Type in "Temari"`,
    TypeKurotsuchi : `Type in "Kurotsuchi"`,
    TypeAkatsuchi : `Type in "Akatsuchi"`,
    TypeKitsuchi : `Type in "Kitsuchi"`,
    TypeTorune : `Type in "Torune"`,
    TypeOrochimaru : `Type in "Orochimaru"`,
    TypeHanzo : `Type in "Hanzo"`,
    TypeSpy : `Type in "Spy"`,
    TypeDanzo : `Type in "Danzo"`,
    TypeJugo : `Type in "Jugo"`,
    TypeHinata : `Type in "Hinata"`,
    TypeSasori : `Type in "Sasori"`,
    TypeJiraiya : `Type in "Jiraiya"`,
    TypeShii : `Type in "Shii"`,
    TypeKiba : `Type in "Kiba"`,
    TypeKirin : `Type in "Kirin"`,
    TypeAo : `Type in "Ao"`,
    TypeAnko : `Type in "Anko"`,
    TypeScroll : `1 Ninjascroll`,
    TypeNinjado : `Type in "ninjado"`,
    SpecialTobi : `[Special]Tobi`,
    SpecialKabuto : `[Special]Kabuto`,
    TypeYin : `[Chakra]Yin`,
    TypeYang : `[Chakra]Yang`,
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    LegendaryItachi : `[Legendary]Itachi = UniqueItachi + HiddenKirin`,
    LegendaryKabuto : `[Legendary]Kabuto = HiddenKabuto + UniqueSasori`,
    LegendaryShisui : `[Legendary]Shisui = UniqueItachi + HiddenDanzo`,
    LegendaryDeidara : `[Legendary]Deidara = UniqueDeidara + HiddenAkatsuchi`,
    LegendaryDodai : `[Legendary]Dodai = HiddenTemari + UniqueNaruto`,
    LegendaryNagato : `[Legendary]Nagato = UniqueNagato + HiddenHanzo + MagicZetsu`,
    LegendaryChiyo : `[Legendary]Chiyo = HiddenSasori + UniqueOrochimaru`,
    LegendaryTsunade : `[Legendary]Tsunade = UniqueSizune + HiddenHashirama`,
    LegendaryTobi : `[Legendary]Tobi = UniqueNoharaRin + HiddenTorune`,
    LegendaryGaara : `[Legendary]Gaara = UniqueGaara + UniqueJugo + UniqueNeji`,
    LegendarySasuke : `[Legendary]Sasuke = UniqueSasuke + UniqueChojuro + UniqueWhiteZetsu`,
    LegendaryKillerBee : `[Legendary]KillerBee = UniqueKillerBee + UniqueSamui + UniqueKisame`,
    LegendaryDarui : `[Legendary]Darui = UniqueSamui + UniqueOmoi + RareKarui + RareKakashi`,
    LegendaryKakashi : `[Legendary]Kakashi = UniqueKakashi + UniqueZabuza + UniqueNoharaRin`,
    LegendarySarutobi : `[Legendary]Sarutobi = UniqueEnma + UniqueYuhiKurenai + RareKotetsu + RareManda`,
    LegendaryShikamaru : `[Legendary]Shikamaru = MagicShikamaru + MagicShikamaru + UniqueHidan + UniqueKakuzu + RareKatsuyu`,
    LegendaryChoji : `[Legendary]Choji = MagicShikamaru + UniqueSai + UniqueNagato + RareAsuma + RareKotetsu`,
    LegendaryYamato : `[Legendary]Yamato = UniqueYamato + UniqueSai + UniqueSizune`,
    LegendaryKushina : `[Legendary]Kushina = UniqueKushina + UniqueNaruto + UniqueJiraiya`,
    LegendaryMinato : `[Legendary]Minato = UniqueKushina + UniqueKillerBee + UniqueEnma`,
    LegendaryRockLee : `[Legendary]RockLee = UniqueRockLee + UniqueNeji + UniqueGaara`,
    LegendaryGuy : `[Legendary]Guy = UniqueRockLee + UniqueTenten + UniqueNeji`,
    LegendaryZabuza : `[Legendary]Zabuza = UniqueZabuza + UniqueRockLee + UniqueSasuke`,
    //below are for tailed beasts

    LegendaryFu : `[Legendary]Fu = SpecialTobi + UniqueKakuzu`,
    LegendaryHan : `[Legendary]Han = SpecialTobi + UniqueItachi`,
    LegendaryRoshi : `[Legendary]Roshi = SpecialTobi + UniqueKisame`,
    LegendaryUtakata : `[Legendary]Utakata = SpecialTobi + UniqueNagato`,
    LegendaryYugito : `[Legendary]Yugito = SpecialTobi + UniqueHidan`,
    LegendaryYagura : `[Legendary]Yagura = SpecialTobi + UniqueNoharaRin`,
    LegendaryMadara : `[Legendary]Madara = SpecialKabuto + UniqueNaruto`,
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    EliteA : `[Elite]A = SpecialKabuto + LegendaryDodai + UniqueKillerBee + NormalNaruto + NormalNaruto`,
    EliteGedoMazo : `[Elite]GedoMazo = LegendaryNagato + LegendaryChoji`,
    EliteGengetsu : `[Elite]Gengetsu = SpecialKabuto + HiddenAo + LegendaryZabuza`,
    EliteGinkaku : `[Elite]Ginkaku = HiddenKitsuchi + LegendaryKabuto + UniqueSamui`,
    EliteGuren : `[Elite]Guren = LegendaryKabuto + UniqueSizune + UniqueGamahiro + HiddenHinata`,
    EliteGari : `[Elite]Gari = UniqueRockLee + SpecialKabuto + LegendaryDeidara + NormalSakura + NormalSakura`,
    EliteHaku : `[Elite]Haku = LegendaryZabuza + LegendaryKakashi`,
    EliteKankuro : `[Elite]Kankuro = UniqueKankuro + LegendaryChiyo + LegendaryGaara`,
    EliteKiba : `[Elite]Kiba = HiddenKiba + HiddenHinata + UniqueShino + UniqueSasuke + MagicKankuro`,
    EliteKinkaku : `[Elite]Kinkaku = LegendaryChoji + LegendaryDarui`,
    EliteKisame : `[Elite]Kisame = UniqueKisame + HiddenShii + LegendaryKillerBee`,
    EliteMifune : `[Elite]Mifune = HiddenHanzo + HiddenDanzo + HiddenOrochimaru`,
    EliteMu : `[Elite]Mu = SpecialKabuto + LegendaryDodai + RareKotetsu + RareIzumo + RareGaara`,
    EliteNaruto : `[Elite]Naruto = HiddenNaruto + HiddenGamakichi + HiddenJiraiya + RareKatsuyu`,
    EliteOrochimaru : `[Elite]Orochimaru = UniqueAnko + LegendaryItachi + HiddenOrochimaru + RareKatsuyu`,
    ElitePakura : `[Elite]Pakura = HiddenMaki + SpecialKabuto + LegendaryZabuza`,
    EliteRasa : `[Elite]Rasa = LegendaryGaara + SpecialKabuto + HiddenTemari`,
    EliteSai : `[Elite]Sai = LegendaryRockLee + UniqueSai + HiddenSasori`,
    EliteShino : `[Elite]Shino = UniqueShino + HiddenTemari + LegendaryTobi`,
    EliteTemari : `[Elite]Temari = HiddenTemari + LegendaryShikamaru + UniqueGaara`,
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    EpicGaara : `[Epic]Gaara = LegendaryGaara + LegendaryKakashi + LegendaryChiyo`,
    EpicGai : `[Epic]Gai = LegendaryGuy + EliteKisame`,
    EpicHashirama : `[Epic]Hashirama = HiddenTobirama + LegendaryYamato + LegendaryTobi + UniqueWhiteZetsu`,
    EpicHidan : `[Epic]Hidan = UniqueHidan + LegendaryDeidara + LegendaryShikamaru + UniqueIno + TypeScroll`,
    EpicHinata : `[Epic]Hinata = HiddenHinata + HiddenKurotsuchi + HiddenGamakichi + HiddenNaruto + UniqueNeji`,
    EpicIno : `[Epic]Ino = UniqueIno + HiddenAo + LegendaryYagura + LegendaryYamato`,
    EpicInoChikaCho : `[Epic]InoChikaCho = LegendaryShikamaru + LegendaryChoji + UniqueIno + TypeYin`,
    EpicItachi : `[Epic]Itachi = LegendaryItachi + LegendaryNagato + LegendaryKillerBee`,
    EpicJiraiya : `[Epic]Jiraiya = HiddenJiraiya + LegendaryTsunade + UniqueEnma + LegendaryGuy`,
    EpicKabuchimaru : `[Epic]Kabuchimaru = LegendaryKabuto + HiddenOrochimaru + HiddenKiba + UniqueSasuke`,
    EpicKakashi : `[Epic]Kakashi = LegendaryKakashi + LegendaryTobi + LegendaryZabuza`,
    EpicKillerA : `[Epic]KillerA = LegendaryDarui + LegendaryKillerBee + HiddenShii + UniqueGaara`,
    EpicKonan : `[Epic]Konan = LegendaryNagato + LegendaryTobi + SpecialTobi + UniqueJiraiya`,
    EpicMadara : `[Epic]Madara = LegendaryMadara + LegendaryDarui + HiddenHashirama + UniqueSasuke`,
    EpicMei : `[Epic]Mei = HiddenAo + LegendaryZabuza + LegendaryTsunade + RareGaara + NormalKarin`,
    EpicMinato : `[Epic]Minato = LegendaryMinato + LegendaryKushina + LegendaryRockLee`,
    EpicMomoshiki : `[Epic]Momoshiki = HiddenKurotsuchi + LegendaryDarui + LegendaryYamato + UniqueChojuro`,
    EpicNaruto : `[Epic]Naruto = HiddenNaruto + LegendaryKushina + LegendaryMinato + RareHinata`,
    EpicObito : `[Epic]Obito = LegendaryTobi + LegendaryGuy + LegendaryKillerBee`,
    EpicOonoki : `[Epic]Oonoki = HiddenKurotsuchi + HiddenKitsuchi + HiddenAkatsuchi + LegendaryDodai`,
    EpicOrochimaru : `[Epic]Orochimaru = HiddenJugo + EliteOrochimaru`,
    EpicPain : `[Epic]Pain = LegendaryNagato + HiddenHinata + HiddenGamakichi + UniqueNaruto + SpecialTobi`,
    EpicRinneMadara : `[Epic]RinneMadara = LegendaryMadara + LegendaryTobi + HiddenTobirama + UniqueWhiteZetsu`,
    EpicSakura : `[Epic]Sakura = NormalSakura + LegendaryChiyo + LegendarySasuke + HiddenGamakichi`,
    EpicSarutobi : `[Epic]Sarutobi = LegendarySarutobi + LegendaryShisui + LegendaryYamato`,
    EpicSasuke : `[Epic]Sasuke = LegendarySasuke + HiddenKirin + HiddenDanzo + HiddenJugo`,
    EpicShisui : `[Epic]Shisui = LegendaryShisui + LegendaryItachi + LegendarySarutobi`,
    EpicTenTails : `[Epic]TenTails = EliteGedoMazo + HiddenGamakichi + UniqueRockLee`,
    EpicTenten : `[Epic]Tenten = UniqueTenten + UniqueKakuzu + HiddenMaki + HiddenKitsuchi + LegendaryDarui`,
    EpicTobirama : `[Epic]Tobirama = HiddenTobirama + EliteNaruto + RareGamaken`,
    EpicToneri : `[Epic]Toneri = HiddenHinata + LegendaryKakashi + LegendaryShikamaru + UniqueSai`,
    EpicTsunade : `[Epic]Tsunade = LegendaryTsunade + LegendaryShikamaru + TypeYang`,
    EpicZetsu : `[Epic]Zetsu = UniqueWhiteZetsu + LegendaryYamato + LegendarySarutobi + HiddenOrochimaru`,
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
}

export {Units}

console.log(Object.keys(Units))

let x = Object.keys(Units).map(y => ({label: y, value: y}) )

console.log(x)

console.log(Units["RareIzumo"].split(/\s\+\s|\s=\s/g))

console.log(/Type/.test("TypeGamakichi"))